pipeline {
  agent any
  options { timestamps() }

  stages {
    stage('Build') {
      steps {
        script {
          def JAVA = tool name: 'JDK21',         type: 'hudson.model.JDK'
          def MVN  = tool name: 'Maven 3.9.x',   type: 'hudson.tasks.Maven$MavenInstallation'
          withEnv(["JAVA_HOME=${JAVA}", "PATH+JAVA=${JAVA}/bin", "PATH+MAVEN=${MVN}/bin"]) {
            sh 'java -version && mvn -v'
            sh 'mvn -B -DskipTests clean package'
          }
        }
      }
    }

    stage('Test') {
      steps {
        script {
          def JAVA = tool name: 'JDK21',         type: 'hudson.model.JDK'
          def MVN  = tool name: 'Maven 3.9.x',   type: 'hudson.tasks.Maven$MavenInstallation'
          withEnv(["JAVA_HOME=${JAVA}", "PATH+JAVA=${JAVA}/bin", "PATH+MAVEN=${MVN}/bin"]) {
            sh 'mvn -B test'
          }
        }
      }
    }

    stage('Deliver') {
      steps { archiveArtifacts artifacts: 'target/*.jar', fingerprint: true }
    }

    stage('Complete') {
      steps { echo '✅ Build pipeline finished.' }
    }
  }
}
